import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import ComplianceRegisterPage from './page';

// Regression coverage for the bug where this page assumed every RECURRING
// category was FILING: it hid the due-date field behind "Computed
// automatically" (true only for FILING, where the scheduler/approval
// bootstrap generates periods) even for a RENEWAL category, whose due date
// is always the certificate's own printed expiry, entered here. These
// tests cover each obligation_kind's form shape plus the picker exclusion
// for FILING + RECURRING (periods for those are generated by the system,
// never registered manually -- createComplianceItem 400s outright).

vi.mock('next/navigation', () => ({
  useRouter: () => ({ push: vi.fn() }),
}));

vi.mock('@/components/layout/DashboardLayout', () => ({
  default: ({ children }: { children: React.ReactNode }) => <div>{children}</div>,
}));

const mockGet = vi.fn();
const mockPost = vi.fn();

const mockUser = { user_id: 'admin-1', email: 'admin@vilag.io', full_name: 'Admin User', role: 'admin', is_active: true };

vi.mock('@/hooks/useAuth', () => ({
  api: {
    get: (...args: unknown[]) => mockGet(...args),
    post: (...args: unknown[]) => mockPost(...args),
  },
  useAuth: () => ({ user: mockUser }),
}));

const FILING_RECURRING_CATEGORY = {
  category_id: 'cat-filing-recurring',
  name: 'VAT',
  regulator: 'ZRA',
  cadence_type: 'RECURRING',
  interval_months: 1,
  due_day_of_month: 18,
  anchor_date: '2026-10-18',
  obligation_kind: 'FILING',
};

const ONE_OFF_CATEGORY = {
  category_id: 'cat-one-off',
  name: 'LAND OCCUPIERS CERTIFICATE',
  regulator: null,
  cadence_type: 'ONE_OFF',
  interval_months: null,
  due_day_of_month: null,
  anchor_date: null,
  obligation_kind: 'FILING',
};

const RENEWAL_CATEGORY = {
  category_id: 'cat-renewal',
  name: 'TCC',
  regulator: 'ZRA',
  cadence_type: 'RECURRING',
  interval_months: 12,
  due_day_of_month: null,
  anchor_date: null,
  obligation_kind: 'RENEWAL',
};

function mockCategories(data: unknown[]) {
  mockGet.mockImplementation((url: string) => {
    if (url.startsWith('/compliance/categories')) return Promise.resolve({ data });
    return Promise.reject(new Error(`Unexpected URL in test: ${url}`));
  });
}

function pdfFile(name = 'evidence.pdf') {
  return new File(['%PDF-1.4'], name, { type: 'application/pdf' });
}

describe('Compliance Register page', () => {
  beforeEach(() => {
    mockGet.mockReset();
    mockPost.mockReset();
  });

  it('excludes FILING + RECURRING categories from the picker entirely', async () => {
    mockCategories([FILING_RECURRING_CATEGORY, ONE_OFF_CATEGORY]);

    const { container } = render(<ComplianceRegisterPage />);

    await waitFor(() => expect(mockGet).toHaveBeenCalled());

    const select = container.querySelector('select[name="category_id"]') as HTMLSelectElement;
    const optionLabels = Array.from(select.options).map((o) => o.textContent);
    expect(optionLabels.join(' ')).not.toContain('VAT');
    expect(optionLabels.join(' ')).toContain('LAND OCCUPIERS CERTIFICATE');
  });

  it('ONE_OFF category: requires a Due Date field and blocks submit with a field-level error when missing', async () => {
    mockCategories([ONE_OFF_CATEGORY]);

    const { container } = render(<ComplianceRegisterPage />);
    await waitFor(() => expect(screen.getByText('Due Date')).toBeInTheDocument());

    const fileInput = container.querySelector('#evidence-file-input') as HTMLInputElement;
    fireEvent.change(fileInput, { target: { files: [pdfFile()] } });

    const form = container.querySelector('form') as HTMLFormElement;
    fireEvent.submit(form);

    expect(await screen.findByText('Due date is required for a one-off category.')).toBeInTheDocument();
    expect(mockPost).not.toHaveBeenCalled();
  });

  it('RENEWAL category: shows a Certificate Expiry Date field with "as printed" helper text, not "Computed automatically"', async () => {
    mockCategories([RENEWAL_CATEGORY]);

    render(<ComplianceRegisterPage />);

    expect(await screen.findByText('Certificate Expiry Date')).toBeInTheDocument();
    expect(screen.getByText('As printed on the certificate.')).toBeInTheDocument();
    expect(screen.queryByText(/Computed automatically/)).not.toBeInTheDocument();
  });

  it('RENEWAL category: a future issued_date is rejected on the field, without calling the API', async () => {
    mockCategories([RENEWAL_CATEGORY]);

    const { container } = render(<ComplianceRegisterPage />);
    await waitFor(() => expect(screen.getByText('Certificate Expiry Date')).toBeInTheDocument());

    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    const futureDate = tomorrow.toISOString().slice(0, 10);

    fireEvent.change(container.querySelector('input[name="issued_date"]') as HTMLInputElement, { target: { value: futureDate } });
    fireEvent.change(container.querySelector('input[name="due_date"]') as HTMLInputElement, { target: { value: '2027-12-31' } });
    fireEvent.change(container.querySelector('#evidence-file-input') as HTMLInputElement, { target: { files: [pdfFile()] } });

    fireEvent.submit(container.querySelector('form') as HTMLFormElement);

    expect(await screen.findByText('Issued date cannot be in the future.')).toBeInTheDocument();
    expect(mockPost).not.toHaveBeenCalled();
  });

  it('RENEWAL category: an expiry date that is not after the issued date is rejected on the field, without calling the API', async () => {
    mockCategories([RENEWAL_CATEGORY]);

    const { container } = render(<ComplianceRegisterPage />);
    await waitFor(() => expect(screen.getByText('Certificate Expiry Date')).toBeInTheDocument());

    fireEvent.change(container.querySelector('input[name="issued_date"]') as HTMLInputElement, { target: { value: '2026-06-01' } });
    fireEvent.change(container.querySelector('input[name="due_date"]') as HTMLInputElement, { target: { value: '2026-06-01' } });
    fireEvent.change(container.querySelector('#evidence-file-input') as HTMLInputElement, { target: { files: [pdfFile()] } });

    fireEvent.submit(container.querySelector('form') as HTMLFormElement);

    expect(await screen.findByText('Expiry date must be after the issued date.')).toBeInTheDocument();
    expect(mockPost).not.toHaveBeenCalled();
  });
});
