-- ============================================================================
-- 001_attendance_schema.sql  —  Attendance module (additive migration)
-- Safe to run multiple times: ADD COLUMN IF NOT EXISTS / CREATE TABLE IF NOT EXISTS
-- ============================================================================

-- ── 1. Attendance columns on users ──────────────────────────────────────────
-- badge_token : UUID embedded in each employee's QR code (auto-generated for all existing users)
-- pin_hash    : bcrypt hash of the 4-digit kiosk PIN (NULL until admin issues a PIN)
-- pin_failed_attempts / pin_locked_until : brute-force lockout
-- pin_must_change : set to TRUE when admin issues or resets a PIN
-- manager_id  : direct-report FK (used for register access scoping)

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS badge_token          UUID        UNIQUE DEFAULT uuid_generate_v4(),
  ADD COLUMN IF NOT EXISTS pin_hash             VARCHAR(255),
  ADD COLUMN IF NOT EXISTS pin_failed_attempts  INT         NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pin_locked_until     TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS pin_must_change      BOOLEAN     NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS manager_id           UUID        REFERENCES users(user_id);

-- ── 2. Attendance terminals (kiosk devices) ──────────────────────────────────
CREATE TABLE IF NOT EXISTS attendance_terminals (
  terminal_id    UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  device_code    VARCHAR(100) UNIQUE NOT NULL,
  terminal_name  VARCHAR(255) NOT NULL,
  -- Optional IP allowlist; empty / NULL = unrestricted
  allowed_ip     INET[],
  is_active      BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ── 3. Raw punch events ──────────────────────────────────────────────────────
-- client_uuid is the idempotency key generated by the kiosk before transmitting.
-- photo_ref is REQUIRED (empty string is rejected at the application layer).
CREATE TABLE IF NOT EXISTS attendance_punches (
  punch_id      UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id       UUID        NOT NULL REFERENCES users(user_id),
  terminal_id   UUID        REFERENCES attendance_terminals(terminal_id),
  punch_type    VARCHAR(20) NOT NULL CHECK (punch_type   IN ('clock_in', 'clock_out')),
  punched_at    TIMESTAMPTZ NOT NULL,
  entry_method  VARCHAR(20) NOT NULL CHECK (entry_method IN ('qr', 'email')),
  photo_ref     VARCHAR(500) NOT NULL,
  client_uuid   UUID        UNIQUE NOT NULL,
  notes         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_punches_user_at  ON attendance_punches(user_id, punched_at);
CREATE INDEX IF NOT EXISTS idx_punches_client   ON attendance_punches(client_uuid);

-- ── 4. Manual adjustments (manager / admin corrections) ─────────────────────
-- punch_id NULL  = 'add_punch' (synthetic; no underlying punch record)
-- corrected_punch_type only used for 'change_type' adjustments
CREATE TABLE IF NOT EXISTS attendance_adjustments (
  adjustment_id         UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  punch_id              UUID        REFERENCES attendance_punches(punch_id),
  user_id               UUID        NOT NULL REFERENCES users(user_id),
  adjusted_by           UUID        NOT NULL REFERENCES users(user_id),
  adjustment_type       VARCHAR(50) NOT NULL CHECK (adjustment_type IN (
                          'correct_time', 'add_punch', 'remove_punch', 'change_type')),
  original_punched_at   TIMESTAMPTZ,
  corrected_punched_at  TIMESTAMPTZ,
  corrected_punch_type  VARCHAR(20) CHECK (corrected_punch_type IN ('clock_in', 'clock_out')),
  reason                TEXT        NOT NULL,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_adj_punch  ON attendance_adjustments(punch_id);
CREATE INDEX IF NOT EXISTS idx_adj_user   ON attendance_adjustments(user_id);
